### ISSUE TITLE
IndexOutOfRangeException when evaluating against schema with more than 512 definitions

### ISSUE THREAD

**Issue by Laniusexcubitor** [json-everything/json-everything#778]
### Nuget Package

JsonSchema.Net

### Package Version

7.x

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

I have a very big schema file which consists of many schemas ($defs)
When trying to evaluate against this schema, I get an `IndexOutOfRangeException`. The exception occurs in [JsonSchema.cs line 571](https://github.com/json-everything/json-everything/blob/b5e3964ffad512cc3531cddd65dd68804ae85856/src/JsonSchema/JsonSchema.cs#L571) because the span used there has a default size of 512, which is not enough in my case.

Validating with this schema does work in 5.x and 6.x

### What did you expect?

I did expect the schema to successfully validate.

### Please add test code or steps to reproduce the behavior.

Here is a dummy schema, that will cause the exception. The schema itself is kind of useless, I just put it together to demonstrate the issue.
[big-schema.json](https://github.com/user-attachments/files/16510360/big-schema.json)

``` CSHARP
var schema = JsonSchema.FromFile("C:\\path\\to\\big-schema.json");
var stream = new FileStream("C:\\path\\to\\any.json", FileMode.Open);
var document = await JsonDocument.ParseAsync(stream); // <-- exception occurs here
```

### Is there any other information you'd like to share regarding this bug?

Perhaps the buffer size used here could be configured and when the buffer is not big enough an exception that explains the problem is thrown.
The default buffer of 512 probably is sufficient in most cases.

Perhaps a simple static configuration where the application can just call something like
```CSHARP
JsonSchemaConfiguration.MinimumSchemaBufferSize = 4096;
```
on startup.

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
I'll see what I can do to make that allocation a bit more dynamic.

**Comment by gregsdennis** [comment]
So, making this dynamic is actually pretty challenging.  Most of the time when I'm allocating a chunk of memory like this, I'm calling `.GetSubschemas()`.  I have no information on how many that could be, so trying to determine the allocation size isn't possible.

I'm also not sure about your suggestion for creating a setting.  It seems like the implementation details are leaking into the API, which goes against my UX sensibilities.

I'm also not a fan of just blowing it out to some large value, either.

Open to other ideas...

(I'm testing this on the infamous FHIR schema, which exhibits the same problem.)

**Comment by Laniusexcubitor** [comment]
Quick thought:
providing the `IMemoryOwner<JsonSchema>` via ref parameter and having a resize method.
```CSHARP
private static void Resize<T>(ref IMemoryOwner<T> owner, ref Span<T> span, int index)
{
	if(index >= owner.Memory.Length)
	{
		var newOwner = MemoryPool<T>.Shared.Rent(index * 2);
		owner.Memory.CopyTo(newOwner.Memory);
		owner.Dispose();
		span = newOwner.Memory.Span;
		owner = newOwner;
	}
}
```

And then call `Resize(ref owner, ref span, i);` before `span[i] = subschema;`  
I would probably also do some benchmarking. to see if this has a negative impact.  
Could be better not to always double the buffer but grow it linearly. Perhaps also check for `MemoryPool<JsonSchema>.Shared.MaxBufferSize` to check for totally crazy schemas.  
As schemas exploding the current buffersize are probably the exception, it could also be better for the majority of cases to catch the `IndexOutOfRangeException` and try again with a bigger buffer. This would not have a performance impact for _normal_ schemas but would make those extremes slower.

**Comment by gregsdennis** [comment]
I thought about doing that, but I didn't like the idea of the performance hit.  Maybe your right in that it would only be an issue for atypically large schemas.

A common practice when resizing arrays is to increment by Fibonnaci values (or at least in a Fibonnaci style).

Not sure I agree with using the exception as a trigger since it's pretty easy to just check, though.

I wonder how the disposal works with what you have.  If the original owner is created as part of a `using` block, I don't think that changing the owner, even through a `ref` parameter, will dispose of the new one.  My guess is it will attempt to dispose the original again.  I'll need to clean that up.

**Comment by Laniusexcubitor** [comment]
Yes, the compiler won't let you use a `using` block variable as `ref` parameter. So you need to go medieval with `try finally` (which will do the right thing).

**Comment by gregsdennis** [comment]
Okay, I think I've come up with a solution: count the subschemas before allocating the memory.  This only happens once upon schema registration.

I've run a benchmark on the test suite, and it doesn't seem to cause any real difference in runtime performance.  Maybe a little more memory, but that's due to some linq use.

| Method          | n  | Mean     | Error    | StdDev   | Gen0        | Gen1      | Allocated |
|---------------- |--- |---------:|---------:|---------:|------------:|----------:|----------:|
| StatusQuo       | 1  | 306.9 ms |  6.07 ms | 10.79 ms |  28000.0000 | 4000.0000 |  74.58 MB |
| CountSubschemas | 1  | 288.5 ms |  5.73 ms | 11.83 ms |  24000.0000 | 5000.0000 |  74.82 MB |
| StatusQuo       | 10 | 857.3 ms | 17.05 ms | 36.70 ms | 190000.0000 | 8000.0000 | 419.02 MB |
| CountSubschemas | 10 | 856.6 ms | 17.12 ms | 45.98 ms | 192000.0000 | 8000.0000 | 423.77 MB |

I think this is acceptable.  I'm going to put up a PR.  @Laniusexcubitor, I'd appreciate if you can pull the PR and run the new code against your schema to verify it solves your problem.

**Comment by Laniusexcubitor** [comment]
That was fast 
I can confirm that this works with my schema 👍
