### ISSUE TITLE
Evaluating from local schema with subschemas

### ISSUE THREAD

**Issue by rico227** [json-everything/json-everything#784]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

7.2.2

### How can I help?  Please provide as much context as possible.

I have a json-schema which is stored locally and should be used to validate json. The schema contains subschemas which again contain subschemas and so on.

According to the documentation I have to register all of the (sub)-schemas to the SchemaRegistry. But I am unable to figure out how to retrieve the parent schema with all its references resolved and evaluate against it.

```c#
var files = Directory.GetFiles("path", "*.json", SearchOption.AllDirectories);
foreach (var file in files)
{
  var schema = JsonSchema.FromFile(file);
  SchemaRegistry.Global.Register(new Uri(file), schema);
}

// Get parent schema with refs?

// Evaluate
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
There are two options that I can see.

### 1. Get by ID

This requires that you know the `$id` URI of the "parent" schema.

```c#
var parentSchema = SchemaRegistry.Global.Get(parentId);
```

Immediately registering a schema right after loading it with `.FromFile()` _should_ register it against the `file:` URI and its defined `$id` URI, if it has one.  So you should be able to retrieve the parent schema if you only have a file name: just convert the file name to a `file:` URI.)

### 2. Load schemas on-demand

Ideally, you want to preload all of the specs.  The spec recommends against resolving `$id` URIs as if they're locators (URLs).  This recommendation is to steer users away from exposing themselves to certain security concerns.

That said, if you're confident that the URIs you'll be resolving are only in the local file system and that doing so is safe, you can use `SchemaRegistry.Global.Fetch` to configure a function to load them as they're needed.

Here are the [docs](https://docs.json-everything.net/schema/basics/#schema-ref-fetch) and [API reference](https://docs.json-everything.net/api/JsonSchema.Net/SchemaRegistry/#properties).

**Comment by rico227** [comment]
@gregsdennis thanks for your quick reply.

I am aware of the first option but the `SchemaRegistry.Global.Get`-method returns an `IBaseDocument` which does not have an `Evaluate`-method.

Regarding the second option I am unsure how to configure the `SchemaRegistry.Global.Fetch`. If I configure it similar to how it is done in the [tests](https://github.com/json-everything/json-everything/blob/83d7f6725c27f355904dbdf7d7badace10b76558/src/JsonSchema.Tests/FetchTests.cs#L42) the validation is only done for the parent schema. The parent schema contains subschemas but they all have the URI of the parent.

```c#
SchemaRegistry.Global.Fetch = uri =>
{
  if (uri.AbsoluteUri == schemaFilePath)
  {
    return JsonSchema.FromFile(schemaFilePath);
  }

  return null;
};

var parentSchema = JsonSchema.FromFile(schemaFilePath);

var validationResults = parentSchema.Evaluate(json);
```

**Comment by gregsdennis** [comment]
> ... the SchemaRegistry.Global.Get-method returns an `IBaseDocument` which does not have an `Evaluate`-method.

`JsonSchema` implements `IBaseDocument`.  In your case, it's quite safe to just cast it.

`IBaseDocument` was introduced to support cases where the root JSON document is not itself a schema, but it _contains_ a schema. An example of this is an OpenAPI document, but it could be any JSON document.  The library also provides a `JsonNodeBaseDocument` to support this.

However since you're not registering anything but `JsonSchema` instances, the registry will only ever return `JsonSchema` instances.

> I am unsure how to configure the `SchemaRegistry.Global.Fetch`.

The purpose of this is to load the schema for the URI that is passed to the function.  The registry has been asked to provide the schema for `uri`, so that's what you need to load.

```c#
SchemaRegistry.Global.Fetch = uri =>
{
    // add some checks... (e.g. ensure it's a file URI, that the file exists, etc.)
    return JsonSchema.FromFile(uri);
};
```

**Comment by rico227** [comment]
Great thanks! 

However I am still unable to resolve the references to the subschemas. E.g. I have an `"additionalProperties": false` in a first level child of the parent schema. But specifing additional properties does not lead to an validation error. 
I have set the `$id` to the respective URI and `$ref` as relative paths like `./sub-schema-dir/subschema.json`.

**Comment by gregsdennis** [comment]
> However I am still unable to resolve the references to the subschemas. E.g. I have an "additionalProperties": false in a first level child of the parent schema. But specifing additional properties does not lead to an validation error.

If you're getting an evaluation result at all (i.e. it's not throwing a `RefResolutionException`), then it's resolving the schemas correctly.  It sounds like you have an error in the schemas.

I'd need to see the schemas (or minimal examples of them) to help with this kind of thing.

**Comment by rico227** [comment]
Yes there are no exceptions.

The parent schema originally looked like this:
```javascript
{
  "$schema": "http://json-schema.org/draft-07/schema#", 
  "title": "parent",
  "description": "parent description",
  "type": "object",
  "required": [
    "reqProp"
  ],
  "properties": {
    "reqProp": {
      "enum": [ "1.0", "2.0", "3.0" ]
    }
  },
  "anyOf": [
    {
      "if": { "properties": { "reqProp": { "const": "1" } } },
      "then": { "$ref": "1.0/sub-schema.json" }
    },
    {
      "if": { "properties": { "reqProp": { "const": "2" } } },
      "then": { "$ref": "2.0/sub-schema.json" }
    },
    {
      "if": { "properties": { "reqProp": { "const": "3" } } },
      "then": { "$ref": "3.0/sub-schema.json" }
    }
  ]
}
``` 

I tried to make the refs resolving by adding and `$id` and `./` in front of the relative paths to the sub-schemas:
```javascript
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "file:///path-to/parent-schema.json",
  "title": "parent",
  "description": "parent description",
  "type": "object",
  "required": [
    "reqProp"
  ],
  "properties": {
    "reqProp": {
      "enum": [ "1.0", "2.0", "3.0" ]
    }
  },
  "anyOf": [
    {
      "if": { "properties": { "reqProp": { "const": "1" } } },
      "then": { "$ref": "./1.0/sub-schema.json" }
    },
    {
      "if": { "properties": { "reqProp": { "const": "2" } } },
      "then": { "$ref": "./2.0/sub-schema.json" }
    },
    {
      "if": { "properties": { "reqProp": { "const": "3" } } },
      "then": { "$ref": "./3.0/sub-schema.json" }
    }
  ]
}
``` 

The first sub level schema for example looks like (note that I tried adding an `$id` and relative paths with `./` like described above aswell):
```javascript
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "sub title",
  "description": "sub description",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "reqProp"
  ],
  "properties": {
    "reqProp": {
      "$ref": "sub-schemas/sub-sub-schema1.json"
    },
    "unrequiredProp": {
      "$ref": "sub-schemas/sub-sub-schema2.json"
    }
  }
}
``` 

As I understand it, there should be a validation error if any other property than `reqProp` and `unrequiredProp` are specified.

**Comment by gregsdennis** [comment]
It doesn't look like you're following the pattern quite correctly.  Have a look at [docs](https://json-schema.org/understanding-json-schema/reference/conditionals#ifthenelse) on the JSON Schema website (search for "Unfortunately, the approach above doesn't scale to more than two countries." and start reading from there for an example of how to do what you're trying to do.

Problems I see,

- You need to use `allOf`, not `anyOf` (See the pattern in the docs.  I think this is actually your culprit.)
- `reqProp` is actually getting two constraints.  These might conflict.
  - the parent schema restricts it to an enum
  - the child schema restricts it to whatever's in `sub-schemas/sub-sub-schema1.json`
- (You also have `reqProp` needing to be `1.0` etc (with a `.0`), but your `if` only has a `1`. I assume this is just a typo in the example.)

The last suggestion I have is to use one of the more verbose output formats: list or hierarchical.  This will give you information on all of the subschema validation results so that you can see where your schema's not behaving as you expect.

**Comment by rico227** [comment]
The `anyOf` was indeed the culprit...
