### ISSUE TITLE
AWS CDK JsonSchema generation

### ISSUE THREAD

**Issue by ivanovvitaly** [json-everything/json-everything#789]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.5.0

### How can I help?  Please provide as much context as possible.

Is there a functionality that allows to generate AWS CDK [JsonSchema ](https://docs.aws.amazon.com/cdk/api/v2/dotnet/api/Amazon.CDK.AWS.APIGateway.JsonSchema.html)classes or are you planning to create some package? Would be very handy

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey @ivanovvitaly.  I don't think I understand your question.  It looks like AWS have already supplied a library for you to use with their systems (though I can't speak to its quality).  This library isn't going to help. Although they both model JSON Schema, they do it quite differently, and they'd be different .net types anyway. 

Also, what are you looking to generate?  This generates schemas from .net classes.

**Comment by ivanovvitaly** [comment]
The problem with AWS library that you have to describe the json schema manually, it doesn't have functionality to generate JsonSchema object from a type, like `JsonSchema.Net.Generation` does e.g.
```
var jsonSchema = schemaBuilder.FromType<MyType>().Build();
```

Looking for something like 
```
var jsonSchema = schemaBuilder.FromType<MyType>().Build();
var awsJsonSchema = convert JsonSchema.Net.Generation.JsonSchema to AWS JsonSchema
```

**Comment by gregsdennis** [comment]
Okay, yeah, generating into someone else's model isn't something I'm open to supporting.  Maintaining changes in my own code is already a lot, and I don't need _also_ maintaining changes in someone else's code.

I recommend that you generate into my `JsonSchema` class (which is what the library already does), and the converting it to the AWS one, if that's what you need.  I'm not sure what the AWS model supports, but you could do something as simple as serializing this model to text, then deserializing into their model.

Personally, I think they should have just used an open source lib (e.g. from this project) rather than building their own.

**Comment by ivanovvitaly** [comment]
Got it, thank you!
