### ISSUE TITLE
Error when evaluating instance against schema

### ISSUE THREAD

**Issue by SStoyanov22** [json-everything/json-everything#800]
### Nuget Package

JsonSchema.Net

### Package Version

7.2.3

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

When trying to use if/else statements in the schema I get different erros.

When I use "**_hasForeignIdentification": { "const": true }_** in the if else statements I get the following error -> _**Expected "true"]}**_.
When I use **_hasForeignIdentification": { enum: [true] }_** in the if else statements, then I get different error -> _**Value should match one of the values specified by the enum**_.

I've been able to validate properly using other libraries/tools and I dont get these errors.

### What did you expect?

I did not expect such errors

### Please add test code or steps to reproduce the behavior.

instance --> https://pastebin.com/FeFhJ9R2
schema   --> https://pastebin.com/7LNgPzqy

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Thanks for reporting.  I don't think this is a bug, but I can't replicate your case because your schemas have references that are unresolvable.

Please update with a [_minimal_ reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) of what you're seeing, and I'll try to address it.

Also, please have a read through my [blog post](https://json-schema.org/blog/posts/interpreting-output), which highlights some of the pitfalls around error messaging and "option" keywords.

**Comment by SStoyanov22** [comment]
Sorry, pasted the wrong schema. Here's the updated one without refs -> [Schema](https://pastebin.com/SgwBRKfv)

**Comment by gregsdennis** [comment]
I'm not sure what the problem is.  `const` and `enum` have different error messages (which [you can configure](https://docs.json-everything.net/schema/basics/#schema-errors) if you like).

When you use `const`, you get a message saying that the value wasn't the expected value.
When you use `enum`, you get a message saying that the value wasn't one of the expected values.

It just happens that the enum you used only has a single value.  That's a special case for `enum` that isn't (and won't be) considered.

**Comment by SStoyanov22** [comment]
Thank you!

**Comment by SStoyanov22** [comment]
I understand why I get those errors but I dont understand the reasoning behind it. I need to exclude those kind of errors. I will give you a simpler example than the initial one.
Schema ->
`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "role": { "enum": [ "HOD", "professor" ] },
    "HOD_Id": { "type": "integer" },
    "professor_Id": { "type": "integer" }
  },
  "if": {
    "properties":
      { "role": { "const": "HOD" }
    }
  },
  "then": { "required": [ "HOD_Id" ] },
  "else": { "required": [ "professor_Id" ] }
}`

Instance ->
'{ "role": "professor", "professor_Id":1 }'

**Comment by gregsdennis** [comment]
The problem (as explained in the blog post) is that there is no general solution to filtering errors to find the "most ideal" or "irrelevant" errors because I, as the library, can't know what your intent is, so I can't determine what's important to you.

My suggestion is to apply some filtering to the errors on your end as you're searching through them.  If you don't want errors from `if` keywords, then filter them out by checking whether the `evaluationPath` contains an `if` segment.  That's why all of that information is given to you.  This is by design.

**Comment by SStoyanov22** [comment]
All clear! Thank you!
