### ISSUE TITLE
Generate schema from JSON sample

### ISSUE THREAD

**Issue by kampilan** [json-everything/json-everything#814]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

7.2.3

### How can I help?  Please provide as much context as possible.

I am successfully using JsonSchema.Net to validate HTTP request bodies. There is a UI that allows users to set the JSON Schema to use for a given endpoint. It would be great to add "Generate Schema from Example JSON" capability. Is there existing capability in JSONSchema.NET to do that? I couldn't find any mention of it in the docs. Before I build it myself I wanted to make sure I was not re-inventing the wheel. 

Thanks
Jim 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there.  Thanks for the idea.

No, `json-everything` doesn't currently support generating a schema from data because it's not possible to generate _quality_ schemas from data.  For example:

```json
{
  "firstName": "John",
  "lastName": "Doe",
  "age": 37
}
```

If we tried to generate a schema from the above data, we might get something like this:

```json
{
  "type": "object",
  "properties": {
    "firstName": {"type": "string"},
    "lastName": {"type": "string},
    "age": {"type": "integer"}
  }
}
```

And that can work, but it's not very good.  It validates some structure, but it doesn't really do anything to validate the range of possible values.

- Are there length or format requirements on first and last name?
- Should the age have a minimum (i.e. 0) or a maximum?
- Is it valid for the age to be a floating point number, but the example we have just happens to be an integer?
- Are other properties allowed?
- Are any properties required?

We can't answer any of these from a single JSON instance.  I have seen a couple projects that can infer a schema given a large data set, but even that depends on widely varying data.

**Comment by kampilan** [comment]
All true!!! But it is a good starting point for them to flesh out from there. I will make assumptions like all items in the HTTP request are required and no additional properties are allowed. In my use case those are reasonable assumptions. Generally, not so much. They are then free to relax those assumptions when they edit.

The real answer to my question is no, but thank you for the full explanation.

Thanks
Jim

**Comment by gregsdennis** [comment]
My experience with giving the user a starting point has been that they take what's generated as production-ready and run with it, often just generating a schema at runtime.  I (and the rest of the JSON Schema team) highly recommend against this practice, and I [say as much](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-disclaimer) in my docs, but it hasn't stopped anyone from doing it anyway.

**Comment by kampilan** [comment]
I did see that! I just didn't put 2 and 2 together. Thank you for your advise.
